# Generated by Django 3.1.4 on 2020-12-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20201224_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='temp_password',
            field=models.BooleanField(default=True),
        ),
    ]
