# Generated by Django 3.1.4 on 2021-01-20 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_soberbro'),
    ]

    operations = [
        migrations.AddField(
            model_name='soberbro',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restapi.member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soberbro',
            name='shift',
            field=models.IntegerField(default=3),
        ),
    ]
