# Generated by Django 3.1.4 on 2021-01-20 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_soberbroshift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soberbro',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.soberbroshift'),
        ),
    ]
