# Generated by Django 3.1.4 on 2021-10-11 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapi', '0010_soberbroshift_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(verbose_name='Event start time. Date in YYYY-MM-DD, time in 24-hour format')),
                ('time_end', models.DateTimeField(verbose_name='Event end time. Date in YYYY-MM-DD, time in 24-hour format')),
                ('guest_count', models.IntegerField(default=0, verbose_name='Automatically generated field that counts the number of guests at the event')),
                ('location', models.CharField(max_length=255, verbose_name='The location of the event')),
                ('comments', models.TextField(verbose_name='Any comments about the event. Notes are appreciated')),
                ('event_name', models.CharField(max_length=255, unique=True, verbose_name='The unique name of the event')),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='abroad_flag',
            field=models.BooleanField(verbose_name="Whether they're abroad"),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=511, verbose_name="The member's home address"),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=127, verbose_name="The member's primary email address. @du.edu emails are okay, but not preferred"),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=127, verbose_name="The member's first name"),
        ),
        migrations.AlterField(
            model_name='member',
            name='inactive_flag',
            field=models.BooleanField(verbose_name="Whether they're inactive"),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=127, verbose_name="The member's last name"),
        ),
        migrations.AlterField(
            model_name='member',
            name='legal_name',
            field=models.CharField(max_length=127, verbose_name="The member's legal name"),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_score',
            field=models.FloatField(verbose_name='The automatic value calculated by the system to assess member involvement'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(db_index=True, max_length=127, verbose_name='The colloquial name of this member.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(db_index=True, max_length=15, verbose_name="The member's cell phone number. It's critical that this is correct."),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(max_length=255, verbose_name="Their position within the chapter. If they don't have one, just use 'Brother'."),
        ),
        migrations.AlterField(
            model_name='member',
            name='present',
            field=models.IntegerField(verbose_name="How many times they've been present at chapter."),
        ),
        migrations.AlterField(
            model_name='member',
            name='rollnumber',
            field=models.IntegerField(verbose_name="The member's number in the roll book"),
        ),
        migrations.AlterField(
            model_name='member',
            name='temp_password',
            field=models.BooleanField(default=True, verbose_name='Whether their password is a temp, prompting a reset at first login.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='The User account associated with this Member.'),
        ),
        migrations.AlterField(
            model_name='soberbroshift',
            name='capacity',
            field=models.IntegerField(default=5, verbose_name='The number of brothers who are able to sign up for this shift.'),
        ),
        migrations.AlterField(
            model_name='soberbroshift',
            name='date',
            field=models.DateField(verbose_name='Date of shift start. Date in YYYY-MM-DD, time in 24-hour format'),
        ),
        migrations.AlterField(
            model_name='soberbroshift',
            name='title',
            field=models.CharField(blank=True, default='Sober Bro Shift', max_length=100, verbose_name='Relatively descriptive name for the shift.'),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=15, verbose_name='The phone number associated with this guest.')),
                ('name', models.CharField(max_length=255, verbose_name='The name associated with this phone number.')),
                ('member', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restapi.member', verbose_name='The member account associated with this phone number, if there is one.')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField(verbose_name='When this guest checked into the event.')),
                ('help_flag', models.BooleanField(default=False, verbose_name='Whether this person requested help at this event.')),
                ('help_flag_raised_at', models.DateTimeField(blank=True, null=True, verbose_name='When the help flag was raised for this person.')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='restapi.event')),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='restapi.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255, verbose_name='The provided alias.')),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='restapi.guest', verbose_name='The guest account associated with this alias.')),
            ],
        ),
    ]
