version: 2.1

orbs:
  python: circleci/python@0.2.1
  slack: circleci/slack@4.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8.2  # primary container for the build job
        auth:
          username: polycole
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      # CircleCI PostgreSQL images available at: https://hub.docker.com/r/circleci/postgres/
      - image: circleci/postgres:9.6.2
        auth:
          username: polycole
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment: # environment variables for the Postgres container.
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./manage.py test
          name: Test
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          custom: |
            {
                "blocks": [
                    {
                        "type": "header",
                        "text": {
                            "type": "plain_text",
                            "text": ":tada: Deployment Successful! :tada:",
                            "emoji": true
                        }
                    },
                    {
                        "type": "section",
                        "fields": [
                            {
                                "type": "mrkdwn",
                                "text": "*Project*:\n$CIRCLE_PROJECT_REPONAME"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*When*:\n$(date +'%m/%d/%Y %T')"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*Tag*:\n$CIRCLE_TAG"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*Branch*:\n$CIRCLE_BRANCH"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*Author*:\n$CIRCLE_USERNAME"
                            }
                        ],
                        "accessory": {
                            "type": "image",
                            "image_url": "https://i.imgur.com/olHpRLd.jpg",
                            "alt_text": "Wooglin CI Success Logo"
                        }
                    },
                    {
                        "type": "actions",
                        "elements": [
                            {
                                "type": "button",
                                "text": {
                                    "type": "plain_text",
                                    "text": "View Job"
                                },
                                "url": "${CIRCLE_BUILD_URL}"
                            }
                        ]
                    }
                ]
            }
          event: pass
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":red_circle: Job Failed. :red_circle:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Job*: ${CIRCLE_JOB}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project*:\n$CIRCLE_PROJECT_REPONAME"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*When*:\n$(date +'%m/%d/%Y %T')"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*:\n$CIRCLE_BRANCH"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author*:\n$CIRCLE_USERNAME"
                    }
                  ],
                  "accessory": {
                    "type": "image",
                    "image_url": "https://i.imgur.com/CXDfXUB.jpg",
                    "alt_text": "Wooglin CI Failure Logo"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Mentions*:\n$SLACK_PARAM_MENTIONS"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }
          event: fail

workflows:
  main:
    jobs:
      - build-and-test
